import { IProject } from './types';

export const projectData: IProject[] = [
  {
    id: 1,
    title: 'Board Masters',
    subtitle: '',
    tags: ['EXPRESS.JS', 'NEXT.JS', 'PRISMA', 'TAILWIND'],
    sourceCode: '',
    liveLink: '',
    status: 'ACTIVE',
    categories: ['BLOCKCHAIN', 'GAME'],
    devices: ['MOBILE', 'WEB'],
    language: ['TYPESCRIPT', 'SOLIDITY'],
    lastContribution: '',
    dateStarted: '',
    images: [],
    coverImg: '/supasave/box.png',
  },
  {
    id: 2,
    title: 'Rampage',
    subtitle: '',
    liveLink: '',
    status: 'NON_ACTIVE',
    sourceCode: '',
    tags: ['HONO.JS', 'POSTGRES', 'ETHERS.JS'],
    categories: [],
    devices: [],
    language: [],
    lastContribution: '',
    dateStarted: '',
    images: [],
    coverImg: '/supasave/box.png',
  },
  {
    id: 3,
    title: 'Xpensa',
    subtitle: 'An invoice management system, where users can easily create invoice. Built for Minipay Hackathon.',
    sourceCode: '',
    liveLink: '',
    tags: ['NEXT.JS', 'PRISMA', 'POSTGRES', 'TAILWIND'],
    status: 'NON_ACTIVE',
    categories: ['FINANCE'],
    devices: ['MOBILE', 'WEB'],
    language: ['TYPESCRIPT', 'SOLIDITY'],
    lastContribution: '',
    dateStarted: '',
    images: [],
    coverImg: '/supasave/box.png',
  },
  {
    id: 4,
    title: 'Stackless',
    subtitle: '',
    sourceCode: '',
    liveLink: '',
    status: 'NON_ACTIVE',
    tags: ['PRISMA', 'TRPC', 'STYLED-COMPONENTS'],
    categories: ['EDUCATION', 'DEVELOPER'],
    devices: ['DESKTOP'],
    language: ['TYPESCRIPT'],
    lastContribution: '',
    dateStarted: '',
    images: [],
    coverImg: '/supasave/box.png',
  },
  {
    id: 5,
    title: 'SupaSave',
    subtitle: 'A Dapp that enables user to lock cUSD ERC20 token for a specified period of time.',
    tags: ['NEXT.JS', 'WAGMI'],
    sourceCode: '',
    liveLink: '',
    status: 'NON_ACTIVE',
    categories: ['BLOCKCHAIN', 'FINANCE'],
    devices: ['WEB'],
    language: ['TYPESCRIPT', 'SOLIDITY'],
    lastContribution: '',
    dateStarted: '',
    images: [],
    coverImg: '/supasave/box.png',
  },
  {
    id: 6,
    title: 'BetaLyf',
    subtitle:
      'A Dapp that helps to bring together healthcare professionals and patients. Book a physician and arrange for a meeting',
    tags: [],
    sourceCode: '',
    liveLink: '',
    status: 'NON_ACTIVE',
    categories: [],
    devices: [],
    language: [],
    lastContribution: '',
    dateStarted: '',
    images: [],
    coverImg: '/supasave/box.png',
  },
  {
    id: 7,
    title: 'Harmony',
    subtitle: '',
    tags: [],
    sourceCode: '',
    liveLink: '',
    status: 'NON_ACTIVE',
    categories: [],
    devices: [],
    language: [],
    lastContribution: '',
    dateStarted: '',
    images: [],
    coverImg: '/supasave/box.png',
  },
  {
    title: 'RxEdu',
    id: 8,
    subtitle: '',
    tags: [],
    sourceCode: '',
    liveLink: '',
    status: 'NON_ACTIVE',
    categories: [],
    devices: [],
    language: [],
    lastContribution: '',
    dateStarted: '',
    images: [],
    coverImg: '/supasave/box.png',
  },
  {
    id: 100,
    title: 'Get2Geda',
    subtitle: '',
    tags: [],
    sourceCode: '',
    liveLink: '',
    status: 'NON_ACTIVE',
    categories: ['EDUCATION'],
    devices: ['MOBILE'],
    language: ['DART'],
    lastContribution: '',
    dateStarted: '',
    images: [],
    coverImg: '/supasave/box.png',
  },
];
