import { IProject } from "./types";

export const projectData: IProject[] = [
  {
    id: 1,
    title: "Board Masters",
    subtitle:
      "A game of chess and checkers that enable users stake cUSD ERC20 token before play",
    tags: ["EXPRESS.JS", "NEXT.JS", "PRISMA", "TAILWIND"],
    sourceCode: "https://github.com/Philix27/Board-Masters",
    liveLink: "https://cheskit.vercel.app/",
    status: "ACTIVE",
    categories: ["BLOCKCHAIN", "GAME"],
    devices: ["MOBILE", "WEB"],
    language: ["TYPESCRIPT", "SOLIDITY"],
    lastContribution: "",
    dateStarted: "",
    images: [],
    coverImg: "/icons/chess.jpeg",
  },
  {
    id: 2,
    title: "Rampage",
    subtitle:
      "An off ramping platform that enables users easily swap crypto-currencies for naira",
    liveLink: "https://ramper-web.vercel.app/",
    status: "NON_ACTIVE",
    sourceCode: "https://github.com/Philix27/rampage",
    tags: ["HONO.JS", "POSTGRES", "ETHERS.JS"],
    categories: ["BLOCKCHAIN"],
    devices: ["MOBILE", "PWA"],
    language: ["TYPESCRIPT"],
    lastContribution: "",
    dateStarted: "",
    images: [],
    coverImg: "/icons/offramp.jpeg",
  },
  {
    id: 3,
    title: "Xpensa",
    subtitle:
      "An invoice management system, where users can easily create invoice. Built for Minipay Hackathon.",
    sourceCode: "https://github.com/Philix27/Xpensa",
    liveLink: "https://xpensa-rosy.vercel.app/",

    tags: ["NEXT.JS", "PRISMA", "POSTGRES", "TAILWIND"],
    status: "NON_ACTIVE",
    categories: ["FINANCE"],
    devices: ["MOBILE", "WEB"],
    language: ["TYPESCRIPT", "SOLIDITY"],
    lastContribution: "",
    dateStarted: "",
    images: [],
    coverImg: "/icons/invoice.jpeg",
  },
  {
    id: 4,
    title: "Stackless",
    subtitle: `Rusty Guide provides a open source 
    learning platform for Rust 
    enthusiast and those who
    are interested in core blockchain technologies.`,
    sourceCode: "https://github.com/Philix27/Stackless-CMS",
    liveLink: "https://rustic-phi.vercel.app/",
    status: "NON_ACTIVE",
    tags: ["PRISMA", "TRPC", "STYLED-COMPONENTS"],
    categories: ["EDUCATION", "DEVELOPER"],
    devices: ["DESKTOP"],
    language: ["TYPESCRIPT"],
    lastContribution: "",
    dateStarted: "",
    images: [],
    coverImg: "/icons/school.jpeg",
  },
  {
    id: 5,
    title: "SupaSave",
    subtitle:
      "A Dapp that enables user to lock cUSD ERC20 token for a specified period of time.",
    tags: ["NEXT.JS", "WAGMI"],
    sourceCode: "https://github.com/Philix27/SupaSave",
    liveLink: "https://supa-save.vercel.app/",
    status: "NON_ACTIVE",
    categories: ["BLOCKCHAIN", "FINANCE"],
    devices: ["WEB"],
    language: ["TYPESCRIPT", "SOLIDITY"],
    lastContribution: "",
    dateStarted: "",
    images: [],
    coverImg: "/supasave/box.png",
  },
  {
    id: 6,
    title: "BetaLyf",
    subtitle: `A Dapp that helps to bring together 
    healthcare professionals
    and patients. Book a
    physician and arrange for a meeting`,
    tags: ["NEXT.JS", "ETHERS.JS", "HACKATHON"],
    sourceCode: "https://github.com/Philix27/betalyf",
    liveLink: "https://peerie.vercel.app/",
    status: "NON_ACTIVE",
    categories: [],
    devices: ["WEB"],
    language: ["TYPESCRIPT", "SOLIDITY"],
    lastContribution: "",
    dateStarted: "",
    images: [],
    coverImg: "/icons/blue-plus.jpeg",
  },
  // {
  //   id: 7,
  //   title: "Harmony",
  //   subtitle: "",
  //   tags: ["TAURI", "NEXT.JS"],
  //   sourceCode: "",
  //   liveLink: "",
  //   status: "NON_ACTIVE",
  //   categories: [],
  //   devices: ["DESKTOP"],
  //   language: ["GO"],
  //   lastContribution: "",
  //   dateStarted: "",
  //   images: [],
  //   coverImg: "/images/project/g2g.jpg",
  // },
  {
    id: 8,
    title: "RxEdu",
    subtitle: "A mobile app that helps Pharmacist prepare for license exams",
    tags: ["FLUTTER", "MONGO_DB", "FIREBASE"],
    sourceCode: "/#",
    liveLink: "/#",
    status: "NON_ACTIVE",
    categories: ["EDUCATION"],
    devices: ["MOBILE"],
    language: ["DART"],
    lastContribution: "",
    dateStarted: "",
    images: [],
    coverImg: "/icons/notes.jpeg",
  },
  {
    id: 9,
    title: "Get2Geda",
    subtitle:
      "A mobile app for students on campus (Delta State University Abraka). For getting live updates and exam past questions.",
    tags: ["FLUTTER", "FIREBASE"],
    sourceCode: "#",
    liveLink: "#",
    status: "NON_ACTIVE",
    categories: ["EDUCATION"],
    devices: ["MOBILE"],
    language: ["DART"],
    lastContribution: "",
    dateStarted: "",
    images: [],
    coverImg: "/images/project/g2g.jpg",
  },
  {
    id: 10,
    title: "MIMS",
    subtitle:
      "A mobile app for students on campus (Delta State University Abraka). For getting live updates and exam past questions.",
    tags: ["FLUTTER", "FIREBASE"],
    sourceCode: "#",
    liveLink: "#",
    status: "NON_ACTIVE",
    categories: ["EDUCATION"],
    devices: ["MOBILE"],
    language: ["DART"],
    lastContribution: "",
    dateStarted: "",
    images: [],
    coverImg: "/images/project/mims.jpg",
  },
];
